From 8080 to 6502
GridAcademy/6502-emulator pull request #1
Opened 2022-04-02 20:52 UTC by anafvana

- Changed instructions from 8080 to 6502
- Added documentation regarding 6502 register architecture
- Created bit setter/unsetter and getter functions

2022-04-02 20:57 UTC, intarga requested changes

2022-04-02 20:57 UTC, intarga commented on architecture.md
> +[http://archive.6502.org/books/mcs6500_family_hardware_manual.pdf](6502 Documentation)
You're missing the last link I sent btw

2022-04-02 20:57 UTC, intarga commented on main.c
> +// Set bit (0-7) in registry
Appreciate these docstrings :+1:

2022-04-02 20:57 UTC, intarga commented on architecture.md
> +[https://www.westerndesigncenter.com/wdc/documentation/w65c02s.pdf](65C02 Documentation) - 65C02 is the static version of the 6502. This manual can be used, as long as the static features are not imp
Also, your links are broken, check the markdown syntax

2022-04-02 21:17 UTC, intarga approved these changes
LGTM, ship it!

2022-04-14 17:00 UTC, odeta939 approved these changes

2022-04-14 17:00 UTC, merged